### ISSUE TITLE
impl Separatable for usize

### ISSUE THREAD

**Issue by JoshBlake** [saghm/rust-separator#1]
It would be helpful to have a usize implementation as well. I have to cast to u64 as a work-around now. Thanks!

**Comment by saghm** [comment]
Oooooh, that's true, not sure how I missed that! I'll try to work on that and get it pushed over the next couple of days.

**Comment by saghm** [comment]
I just pushed an update with the trait implemented for `isize` and `usize`, if you want to take a look.

I'll publish the updated crate sometimes tomorrow, assuming I don't notice any issues with the newly-added functionality.

**Comment by saghm** [comment]
Just pushed version 3.1, which includes te latest changes

**Comment by JoshBlake** [comment]
Great, thanks! Cleaned up my code now.
